settings:
  player-limit: 3

block-world:
  enable: true
  worlds:
    - 'world'

hopper:
  display_name: "<gradient:#FF6B6B:#4ECDC4>VineHopper</gradient>"
  lore:
    - "&#FFFFFF"
    - "&#FFD700✦ Hopper đặc biệt của VineHopper"
    - "&#00FFFF✦ Không thể chế tạo"
    - "&#00FFFF✦ Chỉ có thể nhận từ Admin"
    - "&#FFFFFF"
  transfer_rate: 5
  pickup_rate: 5
  pickup_range: 1
