settings:
  player-limit: 3

block-world:
  enable: true
  worlds:
    - 'world'

hopper:
  display_name: "&aVineHopper"
  lore:
    - "&7"
    - "&7✦ Hopper đặc biệt của VineHopper"
    - "&7✦ Không thể chế tạo"
    - "&7✦ Chỉ có thể nhận từ Admin"
    - "&7"
  transfer_rate: 5
  pickup_rate: 5
  pickup_range: 1
